# 一.创建tensor的方法
1.torch.Tensor(),torch.Tensor([[1,2],[3,4]])

2.torch.eye():创建对角线全1，其余全零的tensor

3.torch.zeros(),torch.zeros_like():参数为一个tensor

4.随机生成 torch.rand():生成服从[0,1)均匀分布的tensor，torch.randn()：生成服从标准正态分布的tensor


In [1]:
import torch
from random import uniform


In [2]:
# torch.normal()
x_dif_nor=torch.normal(mean=torch.Tensor([1.,100.,1000.]),std=torch.Tensor([1.,10.,20.]))
print('tensor value from different nor dis:{0}\n{1}'.format(x_dif_nor.type(),x_dif_nor))


tensor value from different nor dis:torch.FloatTensor
tensor([  2.6642, 108.6001, 988.1343])


torch.Tensor.uniform_():用符合[a,b]间均匀分布的值填充tensor
将tensor使用符合[a,b)间均匀分布的值填充

In [3]:
x_uniform_=torch.Tensor(2,3).uniform_(200,300)
print('x_uniform:{0}\n{1}'.format(x_uniform_.type(),x_uniform_))

x_uniform:torch.FloatTensor
tensor([[228.1739, 233.7821, 299.7418],
        [257.6478, 291.7734, 206.1416]])


生成序列tensor

torch.arange(a,b,step)，[a,b)

In [4]:
x_arange=torch.arange(0,10,2)
print("x_arange:{0}\n{1}".format(x_arange.type(),x_arange))

x_arange:torch.LongTensor
tensor([0, 2, 4, 6, 8])


torch.linspace(a,b,num)
生成将[a,b]切分成num份后，由切分点组成的tensor，默认floatTensor类型

In [5]:
x_linspace=torch.linspace(0,9,10)
print('x_linspace:{0}\n{1}'.format(x_linspace.type(),x_linspace))

x_linspace:torch.FloatTensor
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [6]:
x_randperm=torch.randperm(10)
print("x_randperm:{0}\n{1}".format(x_randperm.type(),x_randperm))

x_randperm:torch.LongTensor
tensor([8, 4, 7, 5, 3, 2, 0, 1, 9, 6])


二.tensor操作

加法操作


In [12]:
y=torch.rand(5,3)
x=torch.rand(5,3)
print(x+y)

result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

y=y.add_(x)
print(y)


tensor([[1.2284, 1.3076, 1.0135],
        [0.1782, 1.2059, 1.0859],
        [0.8393, 0.4367, 0.6118],
        [0.4847, 1.2364, 1.6209],
        [0.7609, 0.6102, 1.7849]])
tensor([[1.2284, 1.3076, 1.0135],
        [0.1782, 1.2059, 1.0859],
        [0.8393, 0.4367, 0.6118],
        [0.4847, 1.2364, 1.6209],
        [0.7609, 0.6102, 1.7849]])
tensor([[1.2284, 1.3076, 1.0135],
        [0.1782, 1.2059, 1.0859],
        [0.8393, 0.4367, 0.6118],
        [0.4847, 1.2364, 1.6209],
        [0.7609, 0.6102, 1.7849]])


索引：访问tensor的一部分
索引出来的结果与原数据共享内存。

https://blog.csdn.net/qimo601/article/details/112185073?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522166692825416782388073353%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=166692825416782388073353&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_click~default-1-112185073-null-null.142^v62^pc_rank_34_queryrelevant25,201^v3^control_2,213^v1^control&utm_term=tensor%E7%B4%A2%E5%BC%95&spm=1018.2226.3001.4187

In [21]:
a=torch.randn(3,4)
print(a)
print(a[0]) #第零行
print(a[:,0]) #第零列
print(a[0][0]) 
print(a[0,-1]) #第零行最后一个数字
print(a[:2]) #前两行
print(a[:2,0:2]) #前两行的前两列
print(a[0:1,:2]) #第零行前两列
print(a[0,:2]) #区别？



tensor([[ 0.6541,  0.9316, -0.0453, -0.2143],
        [-0.8074,  1.5196, -0.0513, -1.0349],
        [-0.5436, -0.3675,  0.9124,  0.2017]])
tensor([ 0.6541,  0.9316, -0.0453, -0.2143])
tensor([ 0.6541, -0.8074, -0.5436])
tensor(0.6541)
tensor(-0.2143)
tensor([[ 0.6541,  0.9316, -0.0453, -0.2143],
        [-0.8074,  1.5196, -0.0513, -1.0349]])
tensor([[ 0.6541,  0.9316],
        [-0.8074,  1.5196]])
tensor([[0.6541, 0.9316]])
tensor([0.6541, 0.9316])


In [26]:
x=torch.arange(15)
print(x.shape)
# tensor形状
print(x.numel())
# tensor元素总数
X=x.reshape(5,3)
print(X)

torch.Size([15])
15
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])


改变形状 view()

In [32]:
from cgi import print_arguments


y=x.view(15)
z=x.view(-1,5)  #-1所指维度可以根据其他维度值推测出来
print(y,z,x.size(),y.size(),z.size())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]) tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]) torch.Size([15]) torch.Size([15]) torch.Size([3, 5])
